image: ${DEVOPS_REGISTRY}usgs/centos:latest

stages:
  - test
  - build
  - deploy

variables:
  CI_REGISTRY: ${CODE_REGISTRY}
  ALGORITHMS_CI_REGISTRY_IMAGE: ${ALGORITHMS_REGISTRY_ADDRESS}
  # docker variables
  DOCKER_DRIVER: overlay2
  FROM_IMAGE: ${DEVOPS_REGISTRY}usgs/centos:7
  # environment variables
  APP_NAME: neic-traveltime

## --------------------------------------------------
# Templates
## --------------------------------------------------
.adjust_image_names:
  before_script:
    - IMAGE_NAME=${APP_NAME}:${CI_COMMIT_REF_SLUG}
    - INTERNAL_IMAGE_NAME=${ALGORITHMS_CI_REGISTRY_IMAGE}/${IMAGE_NAME}
    - STACK_NAME=${APP_NAME}

.deploy:
  cache: {}
  extends:
    - .adjust_image_names
  image: ${CI_REGISTRY}/ghsc/hazdev/container-deploy:latest
  script:
    - mkdir scripts
    # get configuration from the config repository
    - git clone ${ALGORITHMS_CONFIG_REPO_ADDRESS}/${APP_NAME}.git config
    - cp -v
      config/custom.config.sh
      config/custom.funcs.sh
      config/${APP_NAME}.yml
      scripts/.    
    # get the deploy scripts
    - cp -v
      /container-deploy/default.config.sh
      /container-deploy/default.funcs.sh
      /container-deploy/deploy.sh
      scripts/.
    # set varibles
    - export APP_NAME=${APP_NAME}
    - export IMAGE_NAME=${IMAGE_NAME}      
    - export REGISTRY=${ALGORITHMS_CI_REGISTRY_IMAGE}
    - export STACK_NAME=${APP_NAME}
    - export DEBUG='true'
    # do the deployment
    - ./scripts/deploy.sh

  stage: deploy
  tags:
    - deploy

## --------------------------------------------------
# Build Stage
## --------------------------------------------------
Build Docker Image:
  cache: {}
  extends:
    - .adjust_image_names
  image: ${DEVOPS_REGISTRY}docker:19.03-git
  only:
    - development@ghsc/neic/algorithms/neic-traveltime
    - staging@ghsc/neic/algorithms/neic-traveltime
    - production@ghsc/neic/algorithms/neic-traveltime
  script:
    # Build the container
    - docker build
      --pull
      --build-arg FROM_IMAGE=${FROM_IMAGE}
      --build-arg GIT_BRANCH_NAME=${CI_COMMIT_REF_NAME}
      --build-arg GIT_COMMIT_SHA=${CI_COMMIT_SHA}
      --tag local/${IMAGE_NAME} .
   
    ## trivy scan before push
    - wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
    - tar zxvf trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
    # fail LOW,MEDIUM vulnerabilities that have a fix available
    - ./trivy image --exit-code 1 --ignore-unfixed --severity LOW,MEDIUM "${LOCAL_IMAGE}";
    # fail HIGH,CRITICAL vulnerabilities
    - ./trivy image --exit-code 1 --severity HIGH,CRITICAL "${LOCAL_IMAGE}";

    # Tag and Push image to algorithms registry
    - docker tag local/${IMAGE_NAME} ${INTERNAL_IMAGE_NAME}
    - docker push ${INTERNAL_IMAGE_NAME}
    - docker image rm ${INTERNAL_IMAGE_NAME}
  services:
    - alias: docker
      name: ${DEVOPS_REGISTRY}docker:19.03-dind
  stage: build
  tags:
    - build
  variables:
    APP_NAME: neic-traveltime

## --------------------------------------------------
# Test Stage
## --------------------------------------------------
Java Test:
  after_script:
    # runs before cache is saved (copying from .travis.yml)
    - rm -f  "${CI_PROJECT_DIR}/.gradle/caches/modules-2/modules-2.lock"
    - rm -fr "${CI_PROJECT_DIR}/.gradle/caches/*/plugin-resolution/"
  artifacts:
    reports:
      cobertura: build/reports/cobertura/cobertura.xml
      junit: build/test-results/test/TEST-*.xml
  cache:
    paths:
      - .gradle/caches
      - .gradle/wrapper
  image: ${DEVOPS_REGISTRY}usgs/java:11-jdk
  script:
    # run gradle and javadoc
    - export GRADLE_USER_HOME="${CI_PROJECT_DIR}/.gradle"
    - ./gradlew build javadoc
  stage: test
  tags:
    - development

## --------------------------------------------------
# Deploy Stage
## --------------------------------------------------
# Dev deploy
dvbl2 webttt Service:
  extends:
    - .deploy
  tags:
    - deploy
    - development
    - dvbl2
  variables:
    APP_NAME: neic-traveltime
  only:
    - development@ghsc/neic/algorithms/neic-traveltime

# Staging (test) deploy 
dvbld webttt Service:
  extends:
    - .deploy
  tags:
    - deploy
    - staging
    - dvbld
  variables:
    APP_NAME: neic-traveltime
  only:
    - staging@ghsc/neic/algorithms/neic-traveltime

# Production deployment:
mot1 webttt Service:
  extends:
    - .deploy
  tags:
    - deploy
    - production 
    - mot1
  variables:
    APP_NAME: neic-traveltime
  only:
    - production@ghsc/neic/algorithms/neic-traveltime

